language: php
sudo: false

## Cache composer bits
cache:
  directories:
    - $HOME/.composer/cache

## PHP versions we test against
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly

## Build matrix for lowest and highest possible targets
matrix:
  include:
    - php: 5.4
      env: dependencies=lowest
    - php: 5.5
      env: dependencies=lowest
    - php: 5.6
      env: dependencies=lowest
    - php: 7.0
      env: dependencies=lowest
    - php: 7.1
      env: dependencies=lowest
    - php: 7.2
      env: dependencies=lowest
    - php: nightly
      env: dependencies=lowest
    - php: 5.4
      env: dependencies=highest
    - php: 5.5
      env: dependencies=highest
    - php: 5.6
      env: dependencies=highest
    - php: 7.0
      env: dependencies=highest
    - php: 7.1
      env: dependencies=highest
    - php: 7.2
      env: dependencies=highest
    - php: nightly
      env: dependencies=highest
    - name: "Windows"
      os: windows
      language: shell # no built-in php support
      before_install:
        - choco install php
        - choco install composer
        - export PATH="$(powershell -Command '("Process", "Machine" | % { [Environment]::GetEnvironmentVariable("PATH", $_) -Split ";" -Replace "\\$", "" } | Select -Unique | % { cygpath $_ }) -Join ":"')"
  allow_failures:
    - os: windows

## Update composer and run the appropriate composer command
install:
  - composer self-update
  - composer config --unset platform.php
  - if [ -z "$dependencies" ]; then composer install; fi;
  - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest -n; fi;
  - if [ "$dependencies" = "highest" ]; then composer update -n; fi;
  - composer show

## Run the actual test
script: make travis

## Run examples after tests and gather coverage and set it to coverage servers
after_script:
  - php examples/sync.php
  - php examples/async.php
  - make travis-coverage
